/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_azure_gateway_core_LocalBroker */

#ifndef _Included_com_microsoft_azure_gateway_core_LocalBroker
#define _Included_com_microsoft_azure_gateway_core_LocalBroker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_azure_gateway_core_LocalBroker
 * Method:    publishMessage
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_azure_gateway_core_LocalBroker_publishMessage
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
