/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_azure_gateway_core_MessageBus */

#ifndef _Included_com_microsoft_azure_gateway_core_MessageBus
#define _Included_com_microsoft_azure_gateway_core_MessageBus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_azure_gateway_core_MessageBus
 * Method:    publishMessage
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_azure_gateway_core_MessageBus_publishMessage
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
