FROM microsoft/dotnet:2.0.0-runtime

ARG EXE_DIR=.

WORKDIR /app

COPY $EXE_DIR/ ./

RUN apt-get update

RUN apt-get install -y unzip procps

RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg

CMD ["dotnet", "azureiotedge-simulated-temperature-sensor.dll"]