/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_azure_gateway_remote_NanomsgLibrary */

#ifndef _Included_com_microsoft_azure_gateway_remote_NanomsgLibrary
#define _Included_com_microsoft_azure_gateway_remote_NanomsgLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    nn_errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_nn_1errno
  (JNIEnv *, jobject);

/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    nn_strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_nn_1strerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    nn_socket
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_nn_1socket
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    nn_close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_nn_1close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    nn_bind
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_nn_1bind
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    nn_shutdown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_nn_1shutdown
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    nn_send
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_nn_1send
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    nn_recv
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_nn_1recv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microsoft_azure_gateway_remote_NanomsgLibrary
 * Method:    getSymbols
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_microsoft_azure_gateway_remote_NanomsgLibrary_getSymbols
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
